apiVersion: v1
kind: ConfigMap
metadata:
  name: echo-config
  namespace: default
data:
  # SERVICE_NAME.NAMESPACE.svc.cluster.local:SERVICE_PORT
  MONGO_HOST: echo-mongo-cluster-ip-service.default.svc.cluster.local:27017
  MONGO_USERNAME: root
  MONGO_PASSWORD: secret
  MONGO_DATABASE: admin
