apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: default
  name: echo-mongo-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
